services:
  portfolio-astro:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "25001:25001"
    volumes:
      - .:/portfolio-astro:cached
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port 25001
